### ISSUE TITLE
hexo

### ISSUE THREAD

**Issue by qingzhuxin** [qingzhuxin/notes#95]
安装：
```
npm install -g  hexo-cli
```

初始化：
```
hexo init  文件夹
```
生成静态文件
```
hexo g
```

启动本地服务器
```
hexo server
```
重新设置端口
```
hexo -p 5000 server
```

配置hexo,打开hexo文件夹下的_config.yml文件，修改deploy为：
```
deploy:
  type: git 
  repository: https://github.com/qingzhuxin/qingzhuxin.github.io.git
  branch: master
```

部署到Github Page上
```
hexo d
```
部署成功之后
```
hexo clean
```
```
hexo g
```
```
hexo d
```

编写博客
```
hexo new [layout] <title>
```

layout指定文章的布局，默认是post,每种布局的路径：
布局|	路径
---|--
post |	source/_posts
page |	source
draft |	source/_drafts

draft是草稿文件，不会显示在页面上

新建的文件：
```
---
title: {{ title }}   //文章标题
date: {{ date }}   //创建日期
categories:   //分类
tags:    //标签

---
```
